name: Flutter CI

on: push

# jobs:
#   build-and-release-windows:
#     runs-on: windows-latest
#     steps:
#       - name: Clone repository
#       - uses: actions/checkout@v4
#       - name: Set up Flutter
#       - uses: subosito/flutter-action@v2
#         with:
#           channel: 'stable'
#       - name: Install project dependencies
#         run: flutter pub get
#       - name: Generate intermediates
#         run: flutter pub run build_runner build --delete-conflicting-outputs
#       - name: Build artifacts
#         run: flutter build windows --release
#       # - name: Archive Release
#       #   uses: thedoctor0/zip-release@master
#       #   with:
#       #     type: 'zip'
#       #     filename: MacRecoveryX-${{github.ref_name}}-windows.zip
#       #     directory: build/windows/runner/Release
#       # - name: Windows Release
#       #   uses: softprops/action-gh-release@v1
#       #   if: startsWith(github.ref, 'refs/tags/')
#       #   env:
#       #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       #   with:
#     files: build/windows/runner/Release/MacRecoveryX-${{github.ref_name}}-windows.zip
jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows --release

      - name: Create ZIP of Release folder
        run: |
          Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath build/windows/x64/runner/Release/release.zip
        shell: pwsh # Utilisation de PowerShell pour la commande de compression

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-archive@
