name: Flutter Windows Build and Release

on:
  push:
    branches:
      - main # Exécute seulement sur la branche principale, tu peux ajuster selon tes besoins
  pull_request:

jobs:
  build-and-package-windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # Sélectionne le canal Flutter stable pour garantir la stabilité

      - name: Install dependencies
        run: flutter pub get

      - name: Build application for Windows
        run: flutter build windows --release

      - name: Create ZIP of Release folder
        run: |
          Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath build/windows/x64/runner/Release/release.zip
        shell: pwsh # Utilisation de PowerShell pour la commande de compression

      - name: Upload Release ZIP artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-release-${{ github.ref_name }}
          path: build/windows/x64/runner/Release/release.zip
