name: Flutter Windows Build and Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-package-windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Affiche le répertoire et vérifie la présence de pubspec.yaml
        run: |
          echo "Chemin actuel : $(Get-Location)"
          Get-ChildItem -Recurse -Name | Select-String 'pubspec.yaml'
        shell: pwsh

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build application for Windows
        run: flutter build windows --release

      - name: Extract version from pubspec
        id: version
        run: |
          $version = (Select-String -Path ./pubspec.yaml -Pattern 'version:\s*(\d+\.\d+\.\d+)' | ForEach-Object { $_.Matches.Groups[1].Value }).Trim()
          echo "::set-output name=app_version::$version"
        shell: pwsh

      - name: Define the release name
        id: release_name
        run: |
          $date = Get-Date -Format "dd-MM-yy"
          $releaseName = "jib-eyes-${{ steps.version.outputs.app_version }}-$date"
          echo "::set-output name=name::$releaseName"
        shell: pwsh

      - name: Rename and create ZIP of Release folder
        run: |
          $releaseName = "${{ steps.release_name.outputs.name }}"
          Rename-Item -Path build/windows/x64/runner/Release -NewName $releaseName
          Compress-Archive -Path "build/windows/x64/runner/$releaseName/*" -DestinationPath "build/windows/x64/runner/$releaseName.zip"
        shell: pwsh

      - name: Upload Release ZIP artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.release_name.outputs.name }}
          path: build/windows/x64/runner/$releaseName.zip
